### PR TITLE
Fix FWK005 Exception during parallel execution of DocumentBuilder

### PR DESCRIPTION
**Pull request by YatsenkoVladyslav**
Neither **DocumentBuilderFactory** nor **DocumentBuilder** are guaranteed to be **thread-safe**
If we have several **threads** parsing XML, we need to make sure that each thread has its own version of DocumentBuilder.
We only need one of them per **Thread** since we can reuse a DocumentBuilder after we reset it.

### CODE REVIEW

**Comment by drbgfc** [comment]
Hi,
Thanks for this PR.
I am looking to merge it for the next release.

Do you think we might run into the same parallel execution exception in the content validator if we don't apply the update there as well?

See:
https://github.com/onc-healthit/content-validator-api/blob/master/src/main/java/org/sitenv/contentvalidator/service/ContentValidatorService.java

**Comment by YatsenkoVladyslav** [comment]
Hi,thanks for the reply.
With this fix during performance testing we did not find any problems with the FWK005 exception

From my point of view there is no problem with this class
(content-validator-api)

**Comment by drbgfc** [comment]
Apologies - I had actually mean this class in the content validator to consider:
https://github.com/onc-healthit/content-validator-api/blob/develop/src/main/java/org/sitenv/contentvalidator/parsers/CCDAParser.java

**Comment by drbgfc** [comment]
After taking a look, since there is only one path that leads to the builder running a parse in the content-validator, we can't have an issue, so, feel free to disregard that inquiry.

As for this PR to the code-validator. I agree with your assessment and changes.

**Review by drbgfc — APPROVED** [review]

**Pull request merged**
